# ports:
# frontend 3000 or 80
# userservice 5001
# foodservice 5002
# recipeservice 5003
# mealtrackerservice 5004
# mealsuggestion-service 5005
services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedOrigins__Frontend=http://frontend:3000
    env_file: # Move as many env vars as possible to global.env (those that might get changed)
      - global.env
    networks:
      - foodtracker-network

  foodservice:
    build:
      context: ./FoodService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedOrigins__Frontend=http://frontend:3000
    env_file: # Move as many env vars as possible to global.env (those that might get changed)
      - global.env
    networks:
      - foodtracker-network

  recipeservice:
    build:
      context: ./RecipeService
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedOrigins__Frontend=http://frontend:3000
    env_file: # Move as many env vars as possible to global.env (those that might get changed)
      - global.env
    networks:
      - foodtracker-network

  mealtrackerservice:
    build:
      context: ./MealTrackerService
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings__DatabaseName=MealTrackerDatabase
      - AllowedOrigins__Frontend=http://frontend:3000
    env_file: # Move as many env vars as possible to global.env (those that might get changed)
      - global.env
    networks:
      - foodtracker-network

  frontend:
    build:
      context: ./FoodTrackerClient/food_tracker
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "80:80"
    environment:
      - MONGO_DATABASE_NAME=soa_db
    env_file: # Move as many env vars as possible to global.env (those that might get changed)
      - global.env
    networks:
      - foodtracker-network

networks:
  foodtracker-network:
    name: foodtracker-network

include:
  # Some env set in docker-compose.override.yaml
  - ./MealSuggestionService/docker-compose.yaml