services:
  mealsuggestion-service:
    networks:
      - foodtracker-network
      - mealsuggestionservice-network
    env_file:
      - global.env
    ports:
      - "5005:3002"

networks:
  mealsuggestionservice-network:
    driver: bridge