services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_SOA_MTS
    command: mongod --port 27018
    restart: always
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: miha_plemenitas
      MONGO_INITDB_ROOT_PASSWORD: miha_password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  soa-net:
    driver: bridge
